### ISSUE TITLE
Mobile device management and app restrictions 

### ISSUE THREAD

**Issue by a1-day1** [OfficeDev/Office-Add-in-samples#437] opened 2022-11-17 05:23 UTC
> Note: This template is only for reporting bugs about samples in this repo. If you have a product bug to report about Office web Add-ins, please submit the issue at [https://github.com/OfficeDev/office-js/issues](https://github.com/OfficeDev/office-js/issues/new). This will help us respond to your issue faster.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

**URL of sample**

_URL linking to the sample that has the bug._

**Describe the bug**

_A clear and concise description of what the bug is._

**To Reproduce**

1. _Go to '...'_
2. _Click on '....'_
3. _Scroll down to '....'_
4. _See error_

**Expected behavior**

_A clear and concise description of what you expected to happen._

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: ______
- Host [Excel, Word, PowerPoint, etc.]: ______
- Office version number: ______
- Operating System: ______
- Browser (if using Office Online): ______

**Additional context**

_Add any other context about the problem here._

**Comment by AlexJerabek** [comment] 2022-11-17 17:36
Hi @a1-day1,

It's not clear from the title what the issue is. If you could please fill out the issue template, that would be very helpful. I'll close this for now, but reopen it once we get more information.

**Closed by AlexJerabek** 2022-11-17 17:36 UTC
Labels: needs triage :mag:
