### ISSUE TITLE
word-blazor-add-in - The add-in could not be started | Win 11 + VS2022

### ISSUE THREAD

**Issue by MartinHatchL365** [OfficeDev/Office-Add-in-samples#439] opened 2022-11-29 13:24 UTC
[**URL of sample**](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/blazor-add-in/word-blazor-add-in)

On pressing F5 to run the code, Microsoft Word loads and the task pane says:
_The add-in could not be started. Please restart all Office applications and try again_

**To Reproduce**

1. Load Solution
2. Press F5

**Expected behavior**

The add-in should load correctly

**Screenshots**

N/A

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
- Host [Excel, Word, PowerPoint, etc.]: Microsoft Word
- Office version number: Version 2210 (Build 15726.20202 Click-to-Run)
- Operating System: Windows 11
- Browser (if using Office Online): N/A

**Comment by aafvstam** [comment] 2022-11-29 20:48
Is the Solution set to startup the two projects?
What do you see? Do you see Word starting and a browser?
What you should see is the browser starting and loading the Blazor WASM App (indicating that the server is running)
Also you should see Word starting, loading the taskpane.

**Comment by davidchesnut** [comment] 2022-11-29 20:49
Hi @MartinHatchL365, thanks for reporting this! Sometimes when developing and sideloading, a problem in the cache causes issues. You can try [clearing the cache](https://learn.microsoft.com/office/dev/add-ins/testing/clear-cache) and see if that clears up the problem.

In the meantime I'll test it myself and be sure it is working correctly. Thanks!

**Comment by aafvstam** [comment] 2022-11-29 22:54
Built a completely new Windows 11 machine with VS 2022 and Microsoft 365 and tested the sample on that machine. It ran without issues.

The recording of running the sample can be found here:
https://youtu.be/QTbCoQSn5UM

**Comment by cmeyertons** [comment] 2022-11-30 00:02
@aafvstam I am experiencing the same behavior.

On VS2022 17.4.2 and Windows 10.  It appears to have to do w/ debugging the application -- I can get the add-in to load if I "Start without Debugging"

log file:
```log
{"timestamp":1669764481680,"tag":"runtime.welcome","level":1,"message":"js-debug v1.71.0 started","metadata":{"os":"win32 x64","nodeVersion":"v16.14.0","adapterVersion":"1.71.0"}}
{"tag":"dap.receive","timestamp":1669764481616,"metadata":{"connectionId":0,"message":{"type":"request","command":"initialize","arguments":{"pathFormat":"path","clientID":"visualstudio","clientName":"Visual Studio","adapterID":"pwa-chrome","locale":"en-US","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsRunInTerminalRequest":true,"supportsMemoryReferences":true,"supportsProgressReporting":true,"SupportsMessageBox":true,"supportsHandshakeRequest":true,"supportsVsAdditionalBreakpointBinds":true,"supportsHitCountsChange":true,"supportsVsCustomMessages":true,"supportsVariableEnumerators":true,"supportsMapURLToFilePathRequest":true,"supportsLaunchUnelevatedProcessRequest":true,"supportsAccessingSourcesThorughClient":true},"seq":1}},"level":0}
{"tag":"dap.send","timestamp":1669764481618,"metadata":{"connectionId":0,"message":{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":false,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"supportsReadMemoryRequest":true,"supportsWriteMemoryRequest":true,"exceptionBreakpointFilters":[{"filter":"all","label":"Caught Exceptions","default":false,"supportsCondition":true,"description":"Breaks on all throw errors, even if they're caught later.","conditionDescription":"error.name == \"MyError\""},{"filter":"uncaught","label":"Uncaught Exceptions","default":false,"supportsCondition":true,"description":"Breaks only on errors or promise rejections that are not handled.","conditionDescription":"error.name == \"MyError\""}],"supportsStepBack":false,"supportsSetVariable":true,"supportsRestartFrame":true,"supportsGotoTargetsRequest":false,"supportsStepInTargetsRequest":true,"supportsCompletionsRequest":true,"supportsModulesRequest":false,"additionalModuleColumns":[],"supportedChecksumAlgorithms":[],"supportsRestartRequest":true,"supportsExceptionOptions":false,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":false,"supportsDelayedStackTraceLoading":true,"supportsLoadedSourcesRequest":true,"supportsLogPoints":true,"supportsTerminateThreadsRequest":false,"supportsSetExpression":true,"supportsTerminateRequest":false,"completionTriggerCharacters":[".","[","\"","'"],"supportsBreakpointLocationsRequest":true,"supportsClipboardContext":true,"supportsExceptionFilterOptions":true,"supportsDebuggerProperties":true}}},"level":0}
{"tag":"dap.send","timestamp":1669764481619,"metadata":{"connectionId":0,"message":{"seq":2,"type":"event","event":"initialized","body":{}}},"level":0}
{"tag":"dap.receive","timestamp":1669764481662,"metadata":{"connectionId":0,"message":{"type":"request","command":"launch","arguments":{"webRoot":"C:\\Source\\github\\Office-Add-in-samples\\Samples\\blazor-add-in\\word-blazor-add-in\\word-blazor-add-in\\wwwroot","rootPath":"C:\\Source\\github\\Office-Add-in-samples\\Samples\\blazor-add-in\\word-blazor-add-in\\word-blazor-add-in\\wwwroot","__workspaceFolder":"C:\\Source\\github\\Office-Add-in-samples\\Samples\\blazor-add-in\\word-blazor-add-in\\word-blazor-add-in\\wwwroot","runtimeExecutable":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe","runtimeArgs":[],"sourceMaps":true,"url":"https://localhost:7096/","trace":{"logFile":"C:\\Users\\cmeyertons001\\AppData\\Local\\Temp\\visualstudio-js-debugger.txt"},"port":51586,"launchUnelevated":true,"projectGuid":"32482004-f717-4f15-9dab-d70249aff454","userDataDir":"C:\\Users\\cmeyertons001\\AppData\\Local\\Microsoft\\VisualStudio\\17.0_18e78f37\\WebTools\\3C2B947C_8D40A2F2","breakOnLoad":true,"smartStep":true,"continueOnAttach":false,"skipFiles":[],"showAsyncStacks":true,"timeout":60000,"inspectUri":"{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}","__webAssemblyDebugServerPath":"C:\\Users\\cmeyertons001\\.nuget\\packages\\microsoft.aspnetcore.components.webassembly.devserver\\6.0.4\\Tools\\BlazorDebugProxy\\BrowserDebugHost.dll","__startWebAssemblyDebugServer":false,"cleanUp":"wholeBrowser","name":"Launch the JavaScript PWA Debugger from Visual Studio","type":"pwa-chrome","request":"launch","continueOnDisconnect":true},"seq":2}},"level":0}
{"tag":"dap.send","timestamp":1669764481664,"metadata":{"connectionId":0,"message":{"seq":3,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/launch","data":{"type":"pwa-chrome","request":"launch","os":"win32 x64","nodeVersion":"v16.14.0","adapterVersion":"1.71.0","parameters":"{\"type\":\"pwa-chrome\",\"name\":\"<string>\",\"request\":\"launch\",\"trace\":{\"logFile\":\"<string>\"},\"outputCapture\":\"console\",\"timeout\":60000,\"timeouts\":{},\"showAsyncStacks\":true,\"skipFiles\":[],\"smartStep\":true,\"sourceMaps\":true,\"sourceMapRenames\":true,\"pauseForSourceMap\":true,\"resolveSourceMapLocations\":null,\"rootPath\":\"<string>\",\"outFiles\":[\"<string>\",\"<string>\"],\"sourceMapPathOverrides\":{\"webpack:///./~/*\":\"<string>\",\"webpack:////*\":\"<string>\",\"webpack://@?:*/?:*/*\":\"<string>\",\"webpack://?:*/*\":\"<string>\",\"webpack:///([a-z]):/(.+)\":\"<string>\",\"meteor://💻app/*\":\"<string>\"},\"enableContentValidation\":true,\"cascadeTerminateToConfigurations\":[],\"__workspaceFolder\":\"<string>\",\"__breakOnConditionalError\":false,\"address\":\"localhost\",\"port\":51586,\"disableNetworkCache\":true,\"pathMapping\":{},\"url\":\"<string>\",\"restart\":false,\"urlFilter\":\"*\",\"webRoot\":\"<string>\",\"server\":null,\"browserAttachLocation\":\"workspace\",\"targetSelection\":\"automatic\",\"vueComponentPaths\":[\"<string>\",\"<string>\"],\"perScriptSourcemaps\":\"auto\",\"cwd\":null,\"file\":null,\"env\":{},\"includeDefaultArgs\":true,\"runtimeArgs\":[],\"runtimeExecutable\":\"<string>\",\"userDataDir\":\"<string>\",\"browserLaunchLocation\":\"workspace\",\"profileStartup\":false,\"cleanUp\":\"wholeBrowser\",\"launchUnelevated\":true,\"projectGuid\":\"<string>\",\"breakOnLoad\":true,\"continueOnAttach\":false,\"inspectUri\":\"<string>\",\"__webAssemblyDebugServerPath\":\"<string>\",\"__startWebAssemblyDebugServer\":false,\"continueOnDisconnect\":true}"}}}},"level":0}
{"tag":"dap.send","timestamp":1669764481665,"metadata":{"connectionId":0,"message":{"seq":4,"type":"event","event":"output","body":{"category":"console","output":"Verbose logs are written to:\nC:\\Users\\cmeyertons001\\AppData\\Local\\Temp\\visualstudio-js-debugger.txt\n"}}},"level":0}
{"tag":"dap.receive","timestamp":1669764481681,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"AllowOutOfProcessSymbols":1},"seq":3}},"level":0}
{"tag":"dap.receive","timestamp":1669764481682,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"DisableJITOptimization":0},"seq":4}},"level":0}
{"tag":"dap.receive","timestamp":1669764481682,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"EnableFastEvaluate":1},"seq":5}},"level":0}
{"tag":"dap.receive","timestamp":1669764481682,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"InterpreterOptions":1},"seq":6}},"level":0}
{"tag":"dap.receive","timestamp":1669764481682,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"JustMyCodeStepping":1},"seq":7}},"level":0}
{"tag":"dap.receive","timestamp":1669764481683,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"Native.LoadExports":0},"seq":8}},"level":0}
{"tag":"dap.receive","timestamp":1669764481683,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"StopOnExceptionCrossingManagedBoundary":0},"seq":9}},"level":0}
{"tag":"dap.receive","timestamp":1669764481683,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"WarnIfNoUserCodeOnLaunch":1},"seq":10}},"level":0}
{"tag":"dap.receive","timestamp":1669764481683,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"EnableStepFiltering":true},"seq":11}},"level":0}
{"tag":"dap.send","timestamp":1669764481688,"metadata":{"connectionId":0,"message":{"seq":5,"type":"request","command":"launchUnelevated","arguments":{"process":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe","args":["--disable-background-networking","--disable-background-timer-throttling","--disable-backgrounding-occluded-windows","--disable-breakpad","--disable-client-side-phishing-detection","--disable-default-apps","--disable-dev-shm-usage","--disable-renderer-backgrounding","--disable-sync","--metrics-recording-only","--no-first-run","--no-default-browser-check","--user-data-dir=C:\\Users\\cmeyertons001\\AppData\\Local\\Microsoft\\VisualStudio\\17.0_18e78f37\\WebTools\\3C2B947C_8D40A2F2","--remote-debugging-port=51586","about:blank"]}}},"level":0}
{"tag":"dap.receive","timestamp":1669764481704,"metadata":{"connectionId":0,"message":{"type":"response","request_seq":5,"success":false,"command":"launchUnelevated","message":"Unable to cast object of type 'CShellWindows' to type 'CShellWindows'.","body":{},"seq":12}},"level":0}
{"tag":"dap.send","timestamp":1669764482237,"metadata":{"connectionId":0,"message":{"seq":6,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/error","data":{"!error":{"error":{"message":"read ECONNRESET","name":"Error","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)"}},"error":{"error":{"message":"read ECONNRESET","name":"Error","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)"}},"exceptionType":"uncaughtException"}}}},"level":0}
{"tag":"dap.send","timestamp":1669764482237,"message":"Message not sent. Connection was closed.","level":2}
{"tag":"runtime.exception","timestamp":1669764482237,"message":"Unhandled error in debug adapter","metadata":{"message":"read ECONNRESET","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)"},"level":3}
{"tag":"dap.send","timestamp":1669764486622,"metadata":{"connectionId":0,"message":{"seq":7,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/dap/operation","data":{"errors":[],"initialize":{"operation":"initialize","totalTime":3.7,"max":3.7,"avg":3.7,"stddev":null,"count":1,"failed":0},"!initialize.errors":[],"initialize.errors":[],"setDebuggerProperty":{"operation":"setDebuggerProperty","totalTime":13.4,"max":2.5,"avg":1.5,"stddev":0.7,"count":9,"failed":0},"!setDebuggerProperty.errors":[],"setDebuggerProperty.errors":[]}}}},"level":0}
{"tag":"dap.send","timestamp":1669764486622,"message":"Message not sent. Connection was closed.","level":2}

**Comment by davidchesnut** [comment] 2022-11-30 00:55
Hi @cmeyertons It looks like with Windows 10 you might be running an older webview. You can check on [Browsers used by Office Add-ins](https://learn.microsoft.com/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) . Or you can run the add-in and when it opens, click the < in the upper right corner and select **security info**. The runtime should be "Microsoft Edge". If it is anything else it is possible Blazor may not be supported fully (I'd have to do some more research on backwards compatibility with Blazor and Visual Studio debugging.) I tried forcing Word to use the older webview (Microsoft Edge Legacy), and indeed debugging stopped working for me.

**Comment by aafvstam** [comment] 2022-11-30 06:54
Blazor requires WebView2. Older versions of Office do not install WebView2 by default. What is your Office SKU and version?

**Comment by cmeyertons** [comment] 2022-11-30 12:23
@aafvstam @davidchesnut  thank you both very much for the fast feedback, fingers crossed there's a path forward.  Will check my Office version when I get into the office (no pun intended)

For posterity, I was able to get around the Visual Studio prompt `The operation was cancelled` by following the [instructions for configuring the Visual Studio (Windows) timeout](https://learn.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-7.0&tabs=visual-studio#visual-studio-windows-timeout)

**Comment by cmeyertons** [comment] 2022-11-30 14:34
I am on `Microsoft® Excel® for Microsoft 365 MSO (Version 2202 Build 16.0.14931.20806) 64-bit`

Windows Info:
```
Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎10/‎29/‎2021
OS build	19044.2251
Experience	Windows Feature Experience Pack 120.2212.4180.0
```

So I fall under the category of needing WebView2 installed in order to have Office use it

Windows 10 ver. >= 1903,Window 11 | Microsoft 365 ver. >= 16.0.13530.204242 | No | Microsoft Edge1, 3 with original WebView (EdgeHTML)
-- | -- | -- | --
Windows 8.1Windows 10,Windows 11 | Microsoft 365 ver. >= 16.0.13530.204242 | Yes | Microsoft Edge1 with WebView2 (Chromium-based)

I have confirmed I do have WebView2 installed (under Programs & Features I can see `Microsoft Edge WebView2 Runtime`

**Comment by MartinHatchL365** [comment] 2022-11-30 17:48
> Hi @MartinHatchL365, thanks for reporting this! Sometimes when developing and sideloading, a problem in the cache causes issues. You can try [clearing the cache](https://learn.microsoft.com/office/dev/add-ins/testing/clear-cache) and see if that clears up the problem.
> 
> In the meantime I'll test it myself and be sure it is working correctly. Thanks!

Hi... just the OP here as I can see my thread has been hi-jacked 😂😂🤐🤐🙈🙈

I can confirm that a machine reboot cleared the issues. It is possible that the ScriptLab add-in was conflicting in some way, as I couldn't get a TypeScript based "yo office" add-in to load either 🤷‍♂️

**Comment by davidchesnut** [comment] 2022-12-01 18:13
Hi @MartinHatchL365, glad it is working!

**Comment by aafvstam** [comment] 2022-12-01 23:36
> Hi... just the OP here as I can see my thread has been hi-jacked 😂😂🤐🤐🙈🙈

True, @cmeyertons not sure if your issue persists ... If so, for tracking purposes it would be helpful if you created a new issue and like this one, describe the repro steps and add the Windows / Office versions.

By doing so we can close this one and focus on your specific issue as it appears different than the OP issue.

@MartinHatchL365 Good to hear yours was solved!

**Comment by aafvstam** [comment] 2022-12-01 23:36
> Hi... just the OP here as I can see my thread has been hi-jacked 😂😂🤐🤐🙈🙈

True, @cmeyertons not sure if your issue persists ... If so, for tracking purposes it would be helpful if you created a new issue and like this one, describe the repro steps and add the Windows / Office versions.

By doing so we can close this one and focus on your specific issue as it appears different than the OP issue.

@MartinHatchL365 Good to hear yours was solved; a reboot can do magic 😁

**Closed** 2022-12-10 01:01 UTC
Labels: Needs: author feedback, Status: no recent activity, Status: under investigation
