### ISSUE TITLE
Q: Add a styled text with OpenXML (Word Web Add-in)

### ISSUE THREAD

**Issue by yusukemasuda** [OfficeDev/Office-Add-in-samples#223] opened 2021-12-07 21:17 UTC
**Question**

I would talk about a sample below:
- https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/word-add-in-load-and-write-open-xml

I want to add styled text to a document by clicking a button on taskpane.
However it doesn't seems to work as I expected. 
I assume the sample of the code for the button 'Set Styled Text' is what I expected.
However I don't think the code would work as it is explained.

Added text is not styled well. When I selected the added text, the 'Normal' style is selected in style window. I has expected that the text is styled and a style 'Heading 1' is added in the style window. But the both is not being as I expected. Then I save the document, and unzip it, and I checked style.xml also, but I could not find the style I added out. I believed the added xml elements should be saved in the style.xml and document.xml.

I cannot identify whether the code defect or my environment issue. My environment in Japanese may be being affect it.

I wondered it would work the open xml with a style referencing the existing styles, and I modified the code as extract current xml by 'getSelectedDataAsync', and editing xml on the fly (The description in the ms site does not recommend it though). But it didn't work well.

**Comment by RuoyingLiang** [comment] 2021-12-10 07:45
Thanks for reaching out. @davidchesnut , could you help to take a look?

**Comment by yusukemasuda** [comment] 2021-12-13 21:42
@RuoyingLiang @davidchesnut 
Thank you for replying and a person assigned.
I am investigating with my code, but I couldn't find any new things out.
I wondered it would change something if I rebuild environment with Office refreshed up, and I did it.
However, it didn't changed anything.

I got xml by getSelectedDataAsync after I added styled text by setSelectedDataAsync, then the xml didn't include styles I added.
I don't know why the added styles are ignored.

I would share my environment information.
- Windows10
```
Host Name:                 XXXXXXXXX
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:
Registered Organization:   XXXXXXXXX
Product ID:                00329-20000-00001-AA824
Original Install Date:     2021/11/20, 22:51:22
System Boot Time:          2021/12/14, 6:08:46
System Manufacturer:       Microsoft Corporation
System Model:              Virtual Machine
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~2112 Mhz
BIOS Version:              American Megatrends Inc. 090008 , 2018/12/07
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             ja;Japanese
Input Locale:              ja;Japanese
Time Zone:                 (UTC+09:00) Osaka, Sapporo, Tokyo
Total Physical Memory:     6,144 MB
Available Physical Memory: 3,910 MB
Virtual Memory: Max Size:  7,808 MB
Virtual Memory: Available: 5,608 MB
Virtual Memory: In Use:    2,200 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\XXXXXXXXX
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB4586878
                           [02]: KB4497727
                           [03]: KB4586863
                           [04]: KB4592449
Network Card(s):           1 NIC(s) Installed.
                           [01]: Microsoft Hyper-V Network Adapter
                                 Connection Name: イーサネット
                                 DHCP Enabled:    Yes
                                 DHCP Server:     172.19.96.1
                                 IP address(es)
                                 [01]: 172.19.104.53
                                 [02]: fe80::4052:a95c:4298:77f
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```
- Office365
*> wmic product where "Name like '%%Office%%'" get name,version,language*
```
Language  Name                                                                             Version
0         Office 16 Click-to-Run Extensibility Component                                   16.0.14701.20226
1041      Office 16 Click-to-Run Localization Component                                    16.0.14701.20226
0         Office 16 Click-to-Run Licensing Component                                       16.0.14701.20226
1041      Microsoft Visual Studio 2010 Tools for Office Runtime (x64) Language Pack - JPN  10.0.50903
0         Open XML SDK 2.5 for Microsoft Office                                            2.5.5631
0         Microsoft Visual Studio 2010 Tools for Office Runtime (x64)                      10.0.50908
1033      sptools_Microsoft.VisualStudio.OfficeDeveloperTools.Msi                          16.0.29931
```

**Comment by davidchesnut** [comment] 2021-12-14 18:32
Hi @yusukemasuda,

Thanks for noticing this. I've also reproduced this behavior so I'm tagging this as a bug in the sample and investigating. Hope to follow up soon.

Thanks!
David

**Comment by yusukemasuda** [comment] 2021-12-14 19:42
Hello @davidchesnut 

Thank you for the effort to reproduce.
I hope this issue would be solved.

I wondered the target 'style.xml' on below line is a mistake of 'word/style.xml', I changed it, but it was not solved.
https://github.com/OfficeDev/Office-Add-in-samples/blob/5659bf5ef884c2ba239155f711dd4928050c8203/Samples/word-add-in-load-and-write-open-xml/C%23/LoadingAndWritingOOXMLWeb/OOXMLSamples/TextWithStyle.xml#L12

I will inform you what I wonder something, if I have.

Best,
Yusuke

**Comment by davidchesnut** [comment] 2021-12-14 21:32
Hi @yusukemasuda 

Just for more information, you can also add styles with the Word API. Here's a script lab sample that shows how to add heading 2. You may find this easier to work with.

```javascript
async function run() {
  await Word.run(async (context) => {
    let sentence = context.document.body.insertParagraph("To be or not to be", "End");

    // Use styleBuiltIn to use an enumeration of existing styles. If your style is custom make sure to use: range.style = "name of your style";
    sentence.styleBuiltIn = Word.Style.heading2;

    await context.sync();
  });
}
```

However this won't work with Word.Style.heading1. the text will get formatted that way, but it won't reflect in the ribbon (or OOXML on save.) so there seems to be something about the heading 1 style. I'm still following up with the team and hope to post more information soon.

Thanks,
David

**Comment by davidchesnut** [comment] 2021-12-14 21:55
Hi @yusukemasuda,

This code workaround will work if you set the style directly using a text string.

```javascript
async function run() {
  await Word.run(async (context) => {
    let sentence = context.document.body.insertParagraph("To be or not to be", "End");

  sentence.style = "Heading 1";
    await context.sync();
  });
}
```

**Comment by yusukemasuda** [comment] 2021-12-14 22:32
@davidchesnut 

Thank you for the information and sample codes.
I will try it with my code.
However, I want to add my style to a document also.
This way and to use 'style' property in paragraph are utilize existing styles.
Could you tell me how I add style with some javascript api, if you can?

**Comment by davidchesnut** [comment] 2021-12-17 21:49
Hi @yusukemasuda,

You should be able to set any customer styles by using the [Paragraph style property](https://docs.microsoft.com/javascript/api/word/word.paragraph#style). Set it to the string name of the style you want.

BTW: I also found Heading 1 does work. Sometimes you have to save the document and reload for it to reflect in the style pane in the ribbon. Not sure why but at least the OOXML is correct.

Hope this helps,
David

**Comment by yusukemasuda** [comment] 2021-12-20 12:46
Hi @davidchesnut,

Thank you for investigating about my issue.

> BTW: I also found Heading 1 does work. Sometimes you have to save the document and reload for it to reflect in the style pane in the ribbon. Not sure why but at least the OOXML is correct.

Do you mean that the sample may sometimes work?
As you replied, I tried to run the sample again, but it didn't work as well as I had tried before I asked.
I also tried changed the display language and system locale from ja-JP to en-US, and reinstall the office for en-US instead of ja-JP, but it didn't change the result.

The procedures I performed is:
- Run the sample with the code cloned as it is.
- Pressed the button 'Text With Style'.
- A text was inserted, and it seemed to be without style.

I saved it, and unzip it, I checked a XML file 'word/style.xml' in the doc file, I couldn't find the style inserted out anywhere. Also the text in the XML 'word/document.xml' was not specified the style.
The style should decorate has gone somewhere. I don't know why. I don't figure the differenct between you and me out.

I cannot imagine what has been affecting it.
Do you have any findings for it?

And now, I wanted to decorate a text I insert.
Any other way to accomplish that, would help me.

Best,
Yusuke

**Comment by yusukemasuda** [comment] 2022-01-03 20:47
@davidchesnut 
I tried setting style with the style property in paragraph as you told, and I could decorate my paragraphs I added by existing styles.
I could not add a new style to my document, though.
If you can add a new style with JavaScript API to the doc, let me know that, please.

Thanks,
Yusuke

**Comment by davidchesnut** [comment] 2022-01-10 21:09
Hi @yusukemasuda,

If you are creating a completely new, custom style, there's a bit of a workaround where you have to import a document with the style you want using insertFileFromBase64. Juan put together a great answer with lots of details and a Script Lab snippet here: https://stackoverflow.com/questions/68892700/not-able-to-add-styled-text-with-ooxml.

Hope this helps,
David

**Comment by yusukemasuda** [comment] 2022-01-12 20:48
Hello @davidchesnut 

Thank you for providing information.
I want to try the workaround described in stackoverflow though, I cannot take a time to do it now.
I will do when I am free, maybe the end of January.

**Comment by davidchesnut** [comment] 2022-01-31 23:42
Hi @yusukemasuda,

Sounds good, so I'll close this issue for now. But if you still run into any issues, please reopen this issue.

Thanks!
David

**Comment by davidchesnut** [comment] 2022-01-31 23:44
Actually, I'll reopen the issue. Forgot the sample bug. :-) The sample still needs to be updated to use the rich APIs.

**Comment by yusukemasuda** [comment] 2022-02-01 21:22
@davidchesnut 
Thank you for supporting me very well.
I have been tried to add new styles by inserting a document including styles.
However, It hasn't worked well, yet. I am struggling it and I will ask Juan on the stackoverflow topic.

**Comment by ElizabethSamuel-MSFT** [comment] 2022-06-24 21:51
The sample is about OOXML so it doesn't seem to make sense to update to use rich APIs. Maybe an option would be to create a sample that showcases equivalent/similar behavior/functionality using rich APIs.

I'll go ahead and close this as we'll need to create a new sample instead of updating this one.

**Closed by ElizabethSamuel-MSFT** 2022-06-24 21:51 UTC
Labels: bug: sample
